apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "react-fastapi.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "react-fastapi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "react-fastapi.name" . }}
      app.kubernetes.io/component: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "react-fastapi.name" . }}
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . | quote }}
        {{- end }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ if .Values.images.registry }}{{ .Values.images.registry }}/{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}{{ else }}{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.images.frontend.pullPolicy }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "react-fastapi.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "react-fastapi.name" . }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: 80
