services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
