ingress:
  enabled: true
  hosts:
    - host: crdp.local
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api
          pathType: Prefix
          service: backend
